// Copilot's advice: NAF (Non-Adjacent Form) implementation for emp
// Generated by GitHub Copilot (@copilot) for SarK0Y/DLang

module emp_naf;
import std.stdio;
import gmp_z; // uses the same zz/GmpInt wrapper already in the repo

// Simple container for NAF result: two bitmaps (positions with +1 and -1) and length.
struct NafMaps {
    zz pos;    // bits where digit == +1
    zz neg;    // bits where digit == -1
    uint length; // number of positions processed (highest position + 1)
}

/**
 * Compute the Non-Adjacent Form (NAF) decomposition of (target - key).
 *
 * Returns NafMaps where:
 *  - pos.setbit(i) means the NAF digit at position i is +1
 *  - neg.setbit(i) means the NAF digit at position i is -1
 *
 * Encoding note:
 *  - No adjacent non-zero digits will be produced by NAF.
 *  - Use the pair of bitmaps (pos, neg) to reconstruct the signed integer difference.
 */
extern (C) NafMaps naf_maps(zz target, zz key) {
    // Determine sign and work with absolute difference D = abs(target - key)
    bool negative = false;
    zz D;
    if (target < key.ptr) {
        negative = true;
        D = (key - target).dup;
    } else {
        D = (target - key).dup;
    }

    zz pos = zz.mk; // positions carrying +1 (in NAF)
    zz neg = zz.mk; // positions carrying -1 (in NAF)
    auto one = new zz(1);
    uint i = 0;
    // Process until D == 0
    auto _0 = zz.mk;
    while (D > &_0) {
        if (D.tstbit(0)) { // D is odd
            // Look at the low two bits of D to decide whether to use +1 or -1.
            // val = D mod 4 computed from bits 0 and 1
            bool b1 = D.tstbit(1);
            int val = 1 + (b1 ? 2 : 0); // val is 1 or 3
            int u = (val == 1) ? 1 : -1; // u in {+1, -1}

            // If (target - key) was negative, flip the sign of digit.
            if (negative) u = -u;

            if (u == 1) {
                pos.setbit(i);
                D -= one; // D = D - 1
            } else { // u == -1
                neg.setbit(i);
                D += one; // D = D + 1
            }
        }
        // Shift D right by 1 (divide by 2, floor)
        D >>= 1;
        ++i;
    }

    return NafMaps(pos, neg, i);
}

/**
 * Helper: Reconstruct signed integer difference from NAF maps.
 * Returns signed result as zz with sign applied (positive if more +, negative otherwise).
 *
 * This example reconstructs into a (possibly large) zz by summing +/- 2^i for set bits.
 */
zz naf_reconstruct(NafMaps nm) {
    zz res = new zz(0);
    for (uint i = 0; i < nm.length; ++i) {
        if (nm.pos.tstbit(i)) {
            zz step = new zz(1);
            step <<= i;
            res += step;
        } else if (nm.neg.tstbit(i)) {
            zz step = new zz(1);
            step <<= i;
            res -= step;
        }
    }
    return res;
}

unittest {
    auto tst_neg = new zz (1);
    -tst_neg;
    int int_m_1 = -1;
    zz m_1 = new zz ();
    m_1 = "-1";
    tst_neg.name = "tst_neg";
    m_1.name = "minus 1";
    m_1.prnt;
    tst_neg.prnt;
    assert (tst_neg == &m_1);
    writeln("tst: NAF variant");
    auto target = new zz(37); // example values
    auto key = new zz(10);
    auto nm = naf_maps(target, key);
    writeln("positions length: ", nm.length);
    write("pos bits: ");
    for (size_t i = 0; i < nm.length; ++i) {
        if (nm.pos.tstbit(i)) write(i, " ");
    }
    writeln();
    write("neg bits: ");
    for (size_t i = 0; i < nm.length; ++i) {
        if (nm.neg.tstbit(i)) write(i, " ");
    }
    writeln();

    // Check correctness: reconstructed should equal target-key
    auto rec = naf_reconstruct(nm);
    auto expected = (target - key);
    assert(rec == expected, "NAF reconstruction failed");
    writeln("NAF unit test passed.");
}
// Copilot made errors which prevent this file to compile correctly.
